# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/g0-test
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: g0-test-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: g0-test-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run: npm run build
      - run: npm run firebase-deploy --token={'1//03PjBRbhEJMxWCgYIARAAGAMSNwF-L9IrhIFQ4zvTPahOvMgqJlwt8ahEsT1gOdaC556mlrqEh9jlbZPAlGpgtirXEYDBC-jAqJc'}
